name: fewshot
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch==1.8.0
  - torchvision==0.9.0
  - cudatoolkit=10.2
  - pip:
    - human-id==0.1.0.post3
    - kornia==0.5.11
    - munch==2.5.0
    - numpy==1.21.2
    - pillow==8.3.2
    - pytorch-lightning==1.4.9
    - wandb==0.12.4
    - torchmetrics==0.6.0
